### Get all users
GET http://localhost:3000/api/users
Content-Type: application/json

###

### Create a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Josh",
  "email": "joshy@example.com",
  "age": 21,
  "role": "student"
}



### lets send a bad requst
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "not-an-email",
  "age": -5
}


###

### Update a user 
PUT http://localhost:3000/api/users/6a5a3de45d6515c251832ef9
Content-Type: application/json

{
  "age": 22,
  "role": "developer"
}

###

### Delete a user 
DELETE http://localhost:3000/api/users/<id>
Content-Type: application/json
